spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.143:3306/academia?serverTimezone=UTC
    username: root
    password:
  #propiedades para que hibernate cree adecuadamente las instrucciones SQL
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
# Configuracion para registrarse en eureka.
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.143:8761/eureka
  instance:
    instance-id: servicio-cursos-instancia-1
    hostname: 192.168.1.143

# Puerto para la instancia 1.
server:
  port: 8081
