spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tiendavirtual?serverTimezone=UTC
    username: root
    password:

  # Propiedades para que hibernate cree adecuadamente las instrucciones SQL.
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 

# Configuración para registrarse en eureka.
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 7000
      
